name: digital-sensei

services:
  frontend:
    image: ghcr.io/stangerserg/digital_sensei/frontend:latest
    container_name: ds-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - ds-network

  api-gateway:
    image: ghcr.io/stangerserg/digital_sensei/api-gateway:latest
    container_name: ds-api-gateway
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - ds-network
    depends_on:
      - redis
      - orchestrator

  orchestrator:
    image: ghcr.io/stangerserg/digital_sensei/orchestrator:latest
    container_name: ds-orchestrator
    expose:
      - "8001"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - ds-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: ds-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - ds-network

networks:
  ds-network:
    driver: bridge

volumes:
  redis_data:
